FirFirGCD Application: Channel Class Reference
Channel Class Reference
HEPSIM Technologies Library.
#include <tl.h>
Public Member Functions
string getName ()
void setName (string x)
int getId ()
void setId (int x)
int getW_id ()
void setW_id (int x)
int getR_id ()
void setR_id (int x)
int getWidth ()
void setWidth (int x)
int getNum ()
void setNum (int x)
Data Fields
string name
unsigned int id
unsigned int w_id
unsigned int r_id
unsigned int width
unsigned int num
sc_time working_time
double working_energy
Detailed Description
Definition at line 312 of file tl.h.
Member Function Documentation
getId()
int Channel::getId ()
Definition at line 559 of file tl.cpp.
 {
     return this->id;
 }
getName()
string Channel::getName ()
Definition at line 554 of file tl.cpp.
 {
     return this->name;
 }
getNum()
int Channel::getNum ()
Definition at line 579 of file tl.cpp.
 {
     return this->num;
 }
getR_id()
int Channel::getR_id ()
Definition at line 574 of file tl.cpp.
 {
     return this->r_id;
 }
getW_id()
int Channel::getW_id ()
Definition at line 569 of file tl.cpp.
 {
     return this->w_id;
 }
getWidth()
int Channel::getWidth ()
Definition at line 564 of file tl.cpp.
 {
     return this->width;
 }
setId()
void Channel::setId (int x)
Definition at line 589 of file tl.cpp.
 {
     id = x;
 }
Referenced by SystemManager::generateChannelInstances().
setName()
void Channel::setName (string x)
Definition at line 584 of file tl.cpp.
 {
     name = x;
 }
Referenced by SystemManager::generateChannelInstances().
setNum()
void Channel::setNum (int x)
Definition at line 609 of file tl.cpp.
 {
     num = x;
 }
Referenced by SystemManager::generateChannelInstances().
setR_id()
void Channel::setR_id (int x)
Definition at line 604 of file tl.cpp.
 {
     r_id = x;
 }
Referenced by SystemManager::generateChannelInstances().
setW_id()
void Channel::setW_id (int x)
Definition at line 599 of file tl.cpp.
 {
     w_id = x;
 }
Referenced by SystemManager::generateChannelInstances().
setWidth()
void Channel::setWidth (int x)
Definition at line 594 of file tl.cpp.
 {
     width = x;
 }
Referenced by SystemManager::generateChannelInstances().
Field Documentation
id
unsigned int Channel::id
Definition at line 316 of file tl.h.
name
string Channel::name
Definition at line 315 of file tl.h.
num
unsigned int Channel::num
Definition at line 320 of file tl.h.
r_id
unsigned int Channel::r_id
Definition at line 318 of file tl.h.
w_id
unsigned int Channel::w_id
Definition at line 317 of file tl.h.
width
unsigned int Channel::width
Definition at line 319 of file tl.h.
working_energy
double Channel::working_energy
Definition at line 322 of file tl.h.
working_time
sc_time Channel::working_time
Definition at line 321 of file tl.h.
The documentation for this class was generated from the following files:
HepsycodeDesign/src/tl.h
HepsycodeDesign/src/tl.cpp