FirFirGCD Application: ProcessingUnit Class Reference
ProcessingUnit Class Reference
HEPSIM Technologies Library.
#include <tl.h>
Public Member Functions
unsigned int getId ()
void setId (unsigned int c)
string getName ()
void setName (string x)
string getProcessorType ()
void setProcessorType (string x)
float getCost ()
void setCost (float x)
string getISA ()
void setISA (string x)
float getFrequency ()
void setFrequency (float x)
float ** getCC4S ()
void setCC4S (float **x)
float getPower ()
void setPower (float x)
float getMIPS ()
void setMIPS (float x)
float getI4CSmin ()
void setI4CSmin (float x)
float getI4CSmax ()
void setI4CSmax (float x)
float getVdd ()
void setVdd (float x)
float getIdd ()
void setIdd (float x)
sc_time getOverheadCS ()
void setOverheadCS (sc_time x)
Data Fields
string name
unsigned int id
string processorType
float cost
string ISA
float frequency
float ** CC4CS
float Power
float MIPS
float I4CSmin
float I4CSmax
float Vdd
float Idd
sc_time overheadCS
Detailed Description
Definition at line 80 of file tl.h.
Member Function Documentation
getCC4S()
float ** ProcessingUnit::getCC4S ()
Definition at line 129 of file tl.cpp.
 {
     return this->CC4CS;
 }
getCost()
float ProcessingUnit::getCost ()
Definition at line 99 of file tl.cpp.
 {
     return this->cost;
 }
getFrequency()
float ProcessingUnit::getFrequency ()
Definition at line 119 of file tl.cpp.
 {
     return this->frequency;
 }
getI4CSmax()
float ProcessingUnit::getI4CSmax ()
Definition at line 169 of file tl.cpp.
 {
     return this->I4CSmax;
 }
getI4CSmin()
float ProcessingUnit::getI4CSmin ()
Definition at line 159 of file tl.cpp.
 {
     return this->I4CSmin;
 }
getId()
unsigned int ProcessingUnit::getId ()
Definition at line 71 of file tl.cpp.
{
     return this->id;
 }
getIdd()
float ProcessingUnit::getIdd ()
Definition at line 189 of file tl.cpp.
 {
     return this->Idd;
 }
getISA()
string ProcessingUnit::getISA ()
Definition at line 109 of file tl.cpp.
 {
     return this->ISA;
 }
getMIPS()
float ProcessingUnit::getMIPS ()
Definition at line 149 of file tl.cpp.
 {
     return this->MIPS;
 }
getName()
string ProcessingUnit::getName ()
Definition at line 79 of file tl.cpp.
 {
     return this->name;
 }
getOverheadCS()
sc_time ProcessingUnit::getOverheadCS ()
Definition at line 199 of file tl.cpp.
 {
     return this->overheadCS;
 }
getPower()
float ProcessingUnit::getPower ()
Definition at line 139 of file tl.cpp.
 {
     return this->Power;
 }
getProcessorType()
string ProcessingUnit::getProcessorType ()
Definition at line 89 of file tl.cpp.
 {
     return this->processorType;
 }
getVdd()
float ProcessingUnit::getVdd ()
Definition at line 179 of file tl.cpp.
 {
     return this->Vdd;
 }
setCC4S()
void ProcessingUnit::setCC4S (float ** x)
Definition at line 134 of file tl.cpp.
 {
     CC4CS = x;
 }
Referenced by SystemManager::generateBBInstances().
setCost()
void ProcessingUnit::setCost (float x)
Definition at line 104 of file tl.cpp.
 {
     cost = x;
 }
setFrequency()
void ProcessingUnit::setFrequency (float x)
Definition at line 124 of file tl.cpp.
 {
     frequency = x;
 }
Referenced by SystemManager::generateBBInstances().
setI4CSmax()
void ProcessingUnit::setI4CSmax (float x)
Definition at line 174 of file tl.cpp.
 {
     I4CSmax = x;
 }
Referenced by SystemManager::generateBBInstances().
setI4CSmin()
void ProcessingUnit::setI4CSmin (float x)
Definition at line 164 of file tl.cpp.
 {
     I4CSmin = x;
 }
Referenced by SystemManager::generateBBInstances().
setId()
void ProcessingUnit::setId (unsigned int c)
Definition at line 75 of file tl.cpp.
{
     this->id = c;
 }
Referenced by SystemManager::generateBBInstances().
setIdd()
void ProcessingUnit::setIdd (float x)
Definition at line 194 of file tl.cpp.
 {
     Idd = x;
 }
Referenced by SystemManager::generateBBInstances().
setISA()
void ProcessingUnit::setISA (string x)
Definition at line 114 of file tl.cpp.
 {
     ISA = x;
 }
Referenced by SystemManager::generateBBInstances().
setMIPS()
void ProcessingUnit::setMIPS (float x)
Definition at line 154 of file tl.cpp.
 {
     MIPS = x;
 }
Referenced by SystemManager::generateBBInstances().
setName()
void ProcessingUnit::setName (string x)
Definition at line 84 of file tl.cpp.
 {
     name = x;
 }
Referenced by SystemManager::generateBBInstances().
setOverheadCS()
void ProcessingUnit::setOverheadCS (sc_time x)
Definition at line 204 of file tl.cpp.
 {
     overheadCS = x;
 }
Referenced by SystemManager::generateBBInstances().
setPower()
void ProcessingUnit::setPower (float x)
Definition at line 144 of file tl.cpp.
 {
     Power = x;
 }
Referenced by SystemManager::generateBBInstances().
setProcessorType()
void ProcessingUnit::setProcessorType (string x)
Definition at line 94 of file tl.cpp.
 {
     processorType = x;
 }
Referenced by SystemManager::generateBBInstances().
setVdd()
void ProcessingUnit::setVdd (float x)
Definition at line 184 of file tl.cpp.
 {
     Vdd = x;
 }
Referenced by SystemManager::generateBBInstances().
Field Documentation
CC4CS
float** ProcessingUnit::CC4CS
Definition at line 92 of file tl.h.
cost
float ProcessingUnit::cost
Definition at line 89 of file tl.h.
frequency
float ProcessingUnit::frequency
Definition at line 91 of file tl.h.
I4CSmax
float ProcessingUnit::I4CSmax
Definition at line 96 of file tl.h.
I4CSmin
float ProcessingUnit::I4CSmin
Definition at line 95 of file tl.h.
id
unsigned int ProcessingUnit::id
Definition at line 87 of file tl.h.
Idd
float ProcessingUnit::Idd
Definition at line 98 of file tl.h.
ISA
string ProcessingUnit::ISA
Definition at line 90 of file tl.h.
MIPS
float ProcessingUnit::MIPS
Definition at line 94 of file tl.h.
name
string ProcessingUnit::name
Definition at line 86 of file tl.h.
overheadCS
sc_time ProcessingUnit::overheadCS
Definition at line 99 of file tl.h.
Power
float ProcessingUnit::Power
Definition at line 93 of file tl.h.
processorType
string ProcessingUnit::processorType
Definition at line 88 of file tl.h.
Vdd
float ProcessingUnit::Vdd
Definition at line 97 of file tl.h.
The documentation for this class was generated from the following files:
HepsycodeDesign/src/tl.h
HepsycodeDesign/src/tl.cpp